### ISSUE TITLE
Can not get variations

### ISSUE THREAD

**Issue by sarxan26** [yii2tech/ar-variation#1]
Hi Paul!
I want to implement  i18n feature for ActiveRecord class FaqCategory using this extension. Here are my tables:

```
CREATE TABLE `FaqCategory` 
(
    `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
    `name` varchar(255) DEFAULT NULL,
    `icon` varchar(255) DEFAULT NULL,
     PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8

CREATE TABLE 
`FaqCategoryTranslation` 
(
    `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
    `catID` int(10) unsigned DEFAULT NULL,
    `languageID` tinyint(2) unsigned NOT NULL,
    `title` varchar(255) DEFAULT NULL,
    `slug` varchar(255) DEFAULT NULL,
     PRIMARY KEY (`id`),
     KEY `catID` (`catID`) USING BTREE,
     KEY `languageID` (`languageID`),
     CONSTRAINT `FCT_FK1` FOREIGN KEY (`catID`) REFERENCES `FaqCategory` (`id`) ON DELETE             CASCADE ON UPDATE CASCADE,
    CONSTRAINT `FCT_FK2` FOREIGN KEY (`languageID`) REFERENCES `Language` (`id`) ON   DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8

CREATE TABLE `Language` 
(
  `id` tinyint(2) unsigned NOT NULL AUTO_INCREMENT,
  `locale` varchar(2) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8
```

FaqCategory model:

```
class FaqCategory extends \yii\db\ActiveRecord
{

    public function behaviors()
    {
        return [
            'translationBehavior' => [
                'class' => VariationBehavior::className(),
                'variationsRelation' => 'translations',
                'defaultVariationRelation' => 'defaultTranslation',
                'variationOptionReferenceAttribute' => 'languageID',
                'optionModelClass' => Language::className(),
                'defaultVariationOptionReference' => function () {
                    return Yii::$app->language;
                },
                'variationAttributeDefaultValueMap' => [
                    'title' => 'name'
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'FaqCategory';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['icon', 'name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'icon' => 'Icon',
        ];
    }

    public static function find()
    {
        return parent::find()->with('defaultTranslation');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTranslations()
    {
        return $this->hasMany(FaqCategoryTranslation::className(), ['catID' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDefaultTranslation()
    {
        return $this->hasDefaultVariationRelation(); // convert "has many translations" into "has one defaultTranslation"
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFaqs()
    {
        return $this->hasMany(Faq::className(), ['catID' => 'id']);
    }
```

Create action:

```
public function actionCreate()
    {
        $model = new FaqCategory();

        $post = Yii::$app->request->post();
        if ($model->load($post) && Model::loadMultiple($model->getVariationModels(), $post) && $model->save()) {
            return $this->redirect(['index']);
        } else


        return $this->render('create', [
            'model' => $model,
        ]);
    }
```

And view file:

```
<div class="faq-category-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="faq-category-form">

        <?php $form = ActiveForm::begin(); ?>

        <?= $form->field($model, 'name'); ?>

        <? foreach ($model->getVariationModels() as $index => $variationModel): ?>
            <?= $form->field($variationModel, "[{$index}]title")->label($variationModel->getAttributeLabel('title') . ' (' . $variationModel->languageID . ')'); ?>
        <?php endforeach; ?>

        <div class="form-group">
            <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
        </div>

        <?php ActiveForm::end(); ?>

    </div>

</div>
```

In frontend  :

```
 public function actionIndex()
    {
        $categories = FaqCategory::find()->with('translations')->all();
        return $this->render('index', ["categories" => $categories]);

    }
```

View file of actionIndex:

```
<div class="cat-descr"><?= $category->title ?></div>
```

Everything was ok, all data insterted properly to FaqCategoryTranslation table with languageID. But when I want to get these values from translation table, it returns only the value of name field in FaqCategory table. Lastly, I'm not completely understood `AttributeDefaultValueMap`. What is this attribute used for? In other words, if our default app language is for example `en` why not to use `en title` as default.
Thanks!

**Comment by tural-ali** [comment]
yes, having same issue here @klimov-paul

**Comment by klimov-paul** [comment]
Unable to reproduce.

I assume your `defaultVariationOptionReference` is incorrect. Your language reference is integer:

> `languageID` tinyint(2) unsigned NOT NULL,

Which means it has values: 1, 2, 3 etc. While `Yii::$app->language;` returns string: 'en', 'ge', 'fr'.
Thus behavior is unable to find default translation record.

**Comment by sarxan26** [comment]
But in your test case `languageId` is integer:

```
$table = 'ItemTranslation';
        $columns = [
            'itemId' => 'integer',
            'languageId' => 'integer',
            'title' => 'string',
            'description' => 'string',
            'PRIMARY KEY(itemId, languageId)'
        ];
```

In README file `languageId` is `varchar(5)`

How we can do in this case?
If `languageId` is integer.

**Comment by sarxan26** [comment]
If ```languageId``` is ```integer```

**Comment by tural-ali** [comment]
@klimov-paul why did you close the issue?

Then what following line does for behaviour if we use languages char code during translation fetch?

```
            'optionModelClass' => Language::className(),
```

And also, it's totally none-sense to use `languageID` column name with language code. Also in your test cases you used `languageID` as integer. 

https://github.com/yii2tech/ar-variation/blob/master/tests/TestCase.php line 90

**Comment by klimov-paul** [comment]
> Also in your test cases you used languageID as integer.

As well as `defaultVariationOptionReference` is integer:
https://github.com/yii2tech/ar-variation/blob/master/tests/data/Item.php#L29

`defaultVariationOptionReference` should return the value, which matches option reference - it is obvious.

**Comment by tural-ali** [comment]
@klimov-paul  I can't understand logic behind it. If we use static integer for `defaultVariationOptionReference` then why on earth we need `'optionModelClass'`?

I think you need to fix this issue like, by providing current language to configuration. And behaviour has to find ID of provided language from Language table by it's language code.

**Comment by klimov-paul** [comment]
The behavior does not know how to search. That is why you can pass a `callable` as `defaultVariationOptionReference` value in order to provide this logic.

**Comment by turalsprofile** [comment]
What do you mean by `callable`?

**Comment by turalsprofile** [comment]
@klimov-paul 
btw you forgot `return` on https://github.com/yii2tech/ar-variation/blame/master/README.md#L213

**Comment by klimov-paul** [comment]
> What do you mean by callable? 

http://php.net/manual/ru/language.types.callable.php

> If you mean to put function like Language::findOne(), I don't want to search for Laguage id everytime when I call the class. It's will decrease db performance on big projects.

I am not here for the teaching young students the PHP programming. It is performed at other places.
