### ISSUE TITLE
Usage documentation example could be improved

### ISSUE THREAD

**Issue by petzo** [yii2tech/ar-variation#19]
In the example configuration this is proposed as a demo code:
```
'defaultVariationOptionReference' => function() {return Yii::$app->language;},
```
But in conjunction with the sample db structure it does not work.
Problem is that sample code is looking for relation with `languageId = 'en'` (string), but it should be looking for: `languageId = 1` (numeric id pk).
You could improve the documentation by something like:
```
'defaultVariationOptionReference' => function() {
    return Language::findOne(['locale' => Yii::$app->language])->id;
},
```
Could definitely save somebody the headache I had finding this misconfiguration.

**Comment by klimov-paul** [comment]
There is no sense of using numeric ID as `Language` entity primary key locale code is much more practical for this.
Your example will cause performance degradation as it performs extra SQL query for each behavior instance initialization. You should use cache for it.
