### ISSUE TITLE
not saving

### ISSUE THREAD

**Issue by mauglee** [yii2tech/ar-variation#21]
Hello,
following your examples exactly, but here:
```php
$item = new Item();
$item->name = 'new name';
$item->title = 'translation title'; // setup of `$item->defaultTranslation` attribute, creating default variation model
$item->description = 'translation description';
$item->save(); // saving both main model and default variation model
```
nothing is saved. <code>$item</code> errors are:
<pre>
Array
(
    [itemId] => Array
        (
            [0] => Необходимо заполнить «Item ID».
        )
    [languageId] => Array
        (
            [0] => Значение «Language ID» неверно.
        )
)
</pre>
Yii2 version is <code>2.0.14.2</code>

**Comment by mauglee** [comment]
Just figured out.
Regarding <code>ItemTranslation</code> table schema, Gii generates <code>itemId</code> and <code>languageId</code> attributes as required:
```php
class ItemTranslation extends \yii\db\ActiveRecord {
    // ...
    public function rules() {
        return [
            [['itemId', 'languageId', 'title'], 'required'],
            // ...
        ];
    }
    // ...
}
```
Your code example does work if this rule is commented out. But because ItemTranslation model can be created „standalone“ (not as Behavior), those attributes should be required. How to deal with this?

**Comment by klimov-paul** [comment]
Either create a separated models or use validation scenarios.

**Comment by mauglee** [comment]
Thank you for your answer and for Behavior itsef. I suggest you to update README regarding this.
