### ISSUE TITLE
variationSaveFilter with yii2 cache dependencies causes serialization of Closure exception

### ISSUE THREAD

**Issue by raraworks** [yii2tech/ar-variation#23]
### What steps will reproduce the problem?
Trying to use yii2 cache components getOrSet, where value might be a AR query with model, that has VariationBehavior set and variationSaveFilter set to a callable.
The behavior property variationSaveFilter asks for a callable (closure), but cache attempts to serialize it and causes the exception.

### What is the expected result?
The cache component caches the query result.

### What do you get instead?
Exception
Serialization of 'Closure' is not allowed
![image](https://user-images.githubusercontent.com/18421085/47564342-581f4480-d92d-11e8-9ecf-be01e1d33709.png)

Possible fix might be allowing call_user_func_array in:
https://github.com/yii2tech/ar-variation/blob/d614c0a887ff137a125d58b167d1285ce88359cb/src/VariationBehavior.php#L605

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.2.10-0ubuntu0.18.04.1
| Operating system | Linux 4.15.0-38-generic #41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018 x86_64

**Comment by klimov-paul** [comment]
This is expected. If you wish your ActiveRecord instance being able to stored in persistent storage like cache or session, it can not contain closures inside it, including its behavior.
Setup `variationSaveFilter` with reference to static method or model method:

```php
['MyActiveRecord', 'filterVariationSave']
// or
[$this, 'filterVariationSave']
```

**Comment by raraworks** [comment]
Yes, that worked, thank you.
