### ISSUE TITLE
variationOptionReferenceAttribute doesnt account for relation alias

### ISSUE THREAD

**Issue by raraworks** [yii2tech/ar-variation#24]
### What steps will reproduce the problem?
Trying to use multiple LEFT JOINs with an aliased relation for variation relation

### What is the expected result?
Alias to be applied to necessary fields within query

### What do you get instead?
If i use multiple left joins for aliased variation relations within one query i will get ambiguous error for variationOptionReferenceAttribute (lets say language_id);

Say for example:

```
$scheduleItems = Schedule::find()
            ->joinWith(['activity' => function ($q) {
                $q->innerJoinWith('defaultTranslation a');
            }, 'location l' => function ($q2) {
                $q2->innerJoinWith('defaultTranslation l');
            }, 'person' => function ($q3) {
                $q3->innerJoinWith('defaultTranslation p');
            }])
            ->where(['between', 'datetime', $monday, $sunday])
            ->andWhere(['schedule.active' => 1, 'schedule.location_id' => $location->id])
            ->all();
```

The resulting SQL query looks like this:

```
SELECT `schedule`.* FROM `schedule` LEFT JOIN `activity` ON `schedule`.`activity_id` = `activity`.`id` INNER JOIN `activity_translation` `a` ON (`activity`.`id` = `a`.`activity_id`) AND (`language_id`=1) LEFT JOIN `location` `l` ON `schedule`.`location_id` = `l`.`id` INNER JOIN `location_translation` `l` ON (`l`.`id` = `l`.`location_id`) AND (`language_id`=1) LEFT JOIN `person` ON `schedule`.`person_id` = `person`.`id` INNER JOIN `person_translation` `p` ON (`person`.`id` = `p`.`person_id`) AND (`language_id`=1) WHERE (`datetime` BETWEEN '2019-03-11 00:00:00' AND '2019-03-17 23:59:59') AND ((`schedule`.`active`=1) AND (`schedule`.`location_id`=2))
```

As we can see there is no alias for language_id field within ON part of statement.

I think the line responsible for additional constraint addition is here:

https://github.com/yii2tech/ar-variation/blob/d614c0a887ff137a125d58b167d1285ce88359cb/src/VariationBehavior.php#L155

the `$condition` variable does not care about `$variationsRelation` alias.

If i change the variationOptionReferenceAttribute to include tablename within behavior declaration ('variationOptionReferenceAttribute' => 'activity_translation.language_id'), then i receive this error when trying to create new model:

![image](https://user-images.githubusercontent.com/18421085/54264764-7902d200-457c-11e9-84f0-aa643dc3aaef.png)

Let me know if im missing something, or this could be done any other way.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.16.1
| PHP version      | 7.2.7-0ubuntu0.18.04.2
| Operating system | Linux 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64

**Comment by klimov-paul** [comment]
Ambiguous column error resolved by commit 2d001a6e55c94634a192c3250293bc1043216c43

Note that there is no way for `VariationBehavior::hasDefaultVariationRelation()` to handle query table alias, since alias applied after the default variation condition composition.

In your example you should remove alias for 'defaultTranslation' relations, allowing ambiguous column to be resolved using table names.
If is necessary for you to use aliases you should use `variationsRelation` manually applying condition over it.
