### ISSUE TITLE
MySQL 8.0.21 fields name BLOCKER issue

### ISSUE THREAD

**Issue by tural-ali** [yii2tech/ar-variation#25]
Please take a look at the Yii2 issue with the latest MySQL version:

https://github.com/yiisoft/yii2/issues/18171

Changing the main DB configuration and adding `attributes' => [PDO::ATTR_CASE => PDO::CASE_LOWER]` messes up everything with this extension.

Also, @samdark recommended using the latest `dev` version of Yii2. It's given the same result again. 

 Translation of any model returns `null` instead of the real value from the Translation table.

Please check this issue.

**Comment by haroldiedema** [comment]
See https://github.com/yiisoft/yii2/pull/18176

**Comment by tural-ali** [comment]
@haroldiedema I already updated the framework until the latest commit in the master branch!

**Comment by tural-ali** [comment]
@haroldiedema doesn't fix the problem with this extension

**Comment by butkov** [comment]
@turalus look at the comment https://github.com/yiisoft/yii2/commit/f1aaa0de89c017d58afbd565d3ec3529fad6b4ea
As a hotfix I've duplicated commit changes from the method loadTableConstraints() to the findConstraints() method in the same class and now it works for me.
Acctually have a question why the same query is duplicated in the one class?

**Comment by tural-ali** [comment]
@butkov the only thing I know is, this extension completely stopped working after applying the latest changes

**Comment by golam-sorwar** [comment]
@turalus
First find this file location   ```vendor/yiisoft/yii2/db/mysql/Schema.php```

Then add this code  ``$row = array_change_key_case($row, CASE_LOWER);``
![Annotation 2020-07-31 200839](https://user-images.githubusercontent.com/31072206/89042990-a87ccf00-d369-11ea-801b-a1c395e7b9f7.png)

Note: Remove this code first ``'attributes' => [PDO::ATTR_CASE => PDO::CASE_LOWER],``

**Comment by tural-ali** [comment]
@golam-sorwar but it needs to be fixed in the repo

**Comment by tural-ali** [comment]
@golam-sorwar Again, I already fixed it in the main framework. The problem is related to the extension

**Comment by tural-ali** [comment]
@klimov-paul any idea?

**Comment by klimov-paul** [comment]
Most likely you experience this problem due to usage of CamelCase naming for your database columns, e.g. having names like `languageId`, `itemId` and so on.
The problem is the Yii is not able to detect correct column names for ActiveRecord population in case of usage `PDO::CASE_LOWER`.
To illustarate it you can the following code can be used:

```php
$db = Yii::$app->getDb();

$table = 'ItemTranslation';
$columns = [
        'itemId' => 'integer',
        'languageId' => 'integer',
        'title' => 'string',
        'description' => 'string',
        'PRIMARY KEY(itemId, languageId)'
];
$db->createCommand()->createTable($table, $columns)->execute();

$model = new ItemTranslation;
var_dump($model->attributes());

$row = (new Query())
       ->from('ItemTranslation')
        ->limit(1)
        ->one();
var_dump($row);

$model->populateRecord($model, $row);
var_dump($model->attributes);
```

It outputs:

```
array(4) {
  [0]=>
  string(6) "itemId"
  [1]=>
  string(10) "languageId"
  [2]=>
  string(5) "title"
  [3]=>
  string(11) "description"
}
array(4) {
  ["itemid"]=>
  string(1) "1"
  ["languageid"]=>
  string(1) "1"
  ["title"]=>
  string(8) "item1-en"
  ["description"]=>
  string(13) "item1-desc-en"
}
array(4) {
  ["itemId"]=>
  NULL
  ["languageId"]=>
  NULL
  ["title"]=>
  string(8) "item1-en"
  ["description"]=>
  string(13) "item1-desc-en"
}
```

ActiveRecord attribute names are stored as CamelCase, while query result column names are lowercased. Thus some model attributes remain empty.

To fix this you may patch `yii\db\Schema::findColumns()` method lowercasing `field` value:

```php
    protected function findColumns($table)
    {
        $sql = 'SHOW FULL COLUMNS FROM ' . $this->quoteTableName($table->fullName);
        try {
            $columns = $this->db->createCommand($sql)->queryAll();
        } catch (\Exception $e) {
            $previous = $e->getPrevious();
            if ($previous instanceof \PDOException && strpos($previous->getMessage(), 'SQLSTATE[42S02') !== false) {
                // table does not exist
                // https://dev.mysql.com/doc/refman/5.5/en/error-messages-server.html#error_er_bad_table_error
                return false;
            }
            throw $e;
        }
        foreach ($columns as $info) {
            if ($this->db->slavePdo->getAttribute(\PDO::ATTR_CASE) !== \PDO::CASE_LOWER) {
                $info = array_change_key_case($info, CASE_LOWER);
            }

            $info['field'] = strtolower($info['field']); // PATCH for PDO::CASE_LOWER

            $column = $this->loadColumnSchema($info);
            $table->columns[$column->name] = $column;
            if ($column->isPrimaryKey) {
                $table->primaryKey[] = $column->name;
                if ($column->autoIncrement) {
                    $table->sequenceName = '';
                }
            }
        }

        return true;
    }
```

Also note that in this case all column name related configuration for the relation attributes and `VariationBehavior` should be also in lower case, e.g. `languageID` => `languageid` and so on.

> General note: this extension does not use PDO directly, it does not compose SQL queries or operate PDO settings, thus it can not be in conflict with PDO configuration directly anyhow. It operatates the ActiveRecord abstraction provided by Yii, for example  it works fine with MongoDB or Redis.

P.S. I can see not point in usage `PDO::CASE_LOWER` with CamelCase column naming. You should either use snake_case naming for columns or remove lowercasing for them.
