### ISSUE TITLE
Primary key issue

### ISSUE THREAD

**Issue by tural-ali** [yii2tech/ar-variation#3]
Let's say we have structure below. As far as I know, behaviour first creates all `ItemTranslation` rows without `itemId` field, then inserts into `item` itself then updates `ItemTranslation` with id from `item` table.

I did `itemId`, `languageId` primary key as you did. But during `model->save()` error occured: `itemId cannot be empty`.

I removed primary key from those two fields, everything went okay. 

Now the problem is, I don't want to take primary keys from translation table. What am I doing wrong?

```
CREATE TABLE `Item`
(
   `id` integer NOT NULL AUTO_INCREMENT,
   `name` varchar(64) NOT NULL,
   `price` integer,
    PRIMARY KEY (`id`)
) ENGINE InnoDB;

CREATE TABLE `ItemTranslation`
(
   `itemId` integer NOT NULL,
   `languageId` varchar(5) NOT NULL,
   `title` varchar(64) NOT NULL,
   `description` TEXT,
    PRIMARY KEY (`itemId`, `languageId`)
    FOREIGN KEY (`itemId`) REFERENCES `Item` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (`languageId`) REFERENCES `Language` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
) ENGINE InnoDB;
```

**Comment by klimov-paul** [comment]
> As far as I know, behaviour first creates all ItemTranslation rows without itemId field, then inserts into item itself then updates ItemTranslation with id from item table.

That is incorect. Variation models are saved only once.
You should remove `reqiored` rule for the 'itemId' in variation model otherwise it will be unable to pass validation.
