### ISSUE TITLE
Is there anyway to get or set exact variation of model (by language)?

### ISSUE THREAD

**Issue by tural-ali** [yii2tech/ar-variation#4]
For example, if we're using foreach inside `Item` table. And current app language is english. 

Is there any way to get and set russian language variation of current model in every loop?

**Comment by klimov-paul** [comment]
Issue resolved by commit 51af6b82d77fc1f76bd6890cdd1a13c1661b7457

**Comment by tural-ali** [comment]
@klimov-paul thx.
