### ISSUE TITLE
Variation Option query filter

### ISSUE THREAD

**Issue by klimov-paul** [yii2tech/ar-variation#5]
Sometimes it could be necessary to apply extra filter condition on for the options query.
For example: select only active languages or languages of the some group.

**Comment by klimov-paul** [comment]
Issue resolved by commit 21c2ca9b9a4e3dbdb26200b5eaa64b3d8719d40a

**Comment by tural-ali** [comment]
@klimov-paul can you please explain this feature a bit more?
